name: BingoReloaded # the plugins name as it should appear in the plugin list /pl
version: 1.3.0 # the plugin's version
author: Steven
main: io.github.steaf23.bingoreloaded.BingoReloaded
api-version: 1.19

softdepend: [PlaceholderAPI]

permissions:
  bingo.admin:
    description: Access all commands and features.
    default: op
    children:
      bingo.settings: true # used for accessing all settings in ./bingo
      bingo.manager: true # used to create and remove cards and item list in the card creator
  bingo.player:
    description: Players can join teams and play games.
    default: true

commands:
  bingo:
    permission: bingo.player
    description: Used to open the settings menu as well as to start and end the game.
    permission-message: §CYou don't have permission to use this command!
  card:
    permission: bingo.manager
    description: Used to edit and create cards containing itemlists where each list as it's own frequency.
    permission-message: §CYou don't have permission to use this command, you need to be atleast a bingo manager!
  itemlist:
    permission: bingo.manager
    description: Used to edit and create lists containing items to be used in bingo cards.
    permission-message: §CYou don't have permission to use this command, you need to be atleast a bingo manager!
  btc:
    permission: bingo.player
    description: Used to toggle team chat when a game is active
    permission-message: §CYou don't have permission to use this command!