name: BingoReloaded # the plugins name as it should appear in the plugin list /pl
version: 2.0.0 # the plugin's version
author: Steven
main: io.github.steaf23.bingoreloaded.BingoReloaded
api-version: 1.19

softdepend: [PlaceholderAPI]

permissions:
  bingo.admin:
    description: Access all commands and features.
    default: op
    children:
      bingo.settings: true # used for accessing all settings in ./bingo
      bingo.manager: true # used to create and remove cards and item list in the card creator
  bingo.player:
    description: Players can join teams and play games.
    default: true

commands:
  autobingo:
    permission: bingo.admin
    description: Used to start and manage settings for bingo games through commands only
    permission-message: §CYou don't have permission to use this command!
  bingo:
    permission: bingo.player
    description: Used to open the settings menu as well as to start and end the game.
    permission-message: §CYou don't have permission to use this command!
  btc:
    permission: bingo.player
    description: Used to toggle team chat when a game is active
    permission-message: §CYou don't have permission to use this command!
  bingobot:
    permission: bingo.admin
    description: Create fake players to join teams and complete tasks, for debugging purposes
  btp:
    permission: bingo.player
    description: Used to teleport to teammates
    permission-message: §CYou don't have permission to use this command!