package io.github.steaf23.bingoreloaded.lib.api.statistics;

import java.util.Map;

public class StatisticsKeyConverter
{
    private static final Map<VanillaStatistic, String> statistics = Map.<VanillaStatistic, String>ofEntries(
            Map.entry(VanillaStatistics.DROP, "dropped"),
            Map.entry(VanillaStatistics.PICKUP, "picked_up"),
            Map.entry(VanillaStatistics.USE_ITEM, "used"),
            Map.entry(VanillaStatistics.BREAK_ITEM, "broken"),
            Map.entry(VanillaStatistics.CRAFT_ITEM, "crafted"),
            Map.entry(VanillaStatistics.KILL_ENTITY, "killed"),
            Map.entry(VanillaStatistics.ENTITY_KILLED_BY, "killed_by"),
            Map.entry(VanillaStatistics.MINE_BLOCK, "mined"),
            Map.entry(VanillaStatistics.DAMAGE_DEALT, "damage_dealt"),
            Map.entry(VanillaStatistics.DAMAGE_TAKEN, "damage_taken"),
            Map.entry(VanillaStatistics.DAMAGE_DEALT_ABSORBED, "damage_dealt_absorbed"),
            Map.entry(VanillaStatistics.DAMAGE_DEALT_RESISTED, "damage_dealt_resisted"),
            Map.entry(VanillaStatistics.DAMAGE_RESISTED, "damage_resisted"),
            Map.entry(VanillaStatistics.DAMAGE_ABSORBED, "damage_absorbed"),
            Map.entry(VanillaStatistics.DAMAGE_BLOCKED_BY_SHIELD, "damage_blocked_by_shield"),
            Map.entry(VanillaStatistics.TALKED_TO_VILLAGER, "talked_to_villager"),
            Map.entry(VanillaStatistics.TRADED_WITH_VILLAGER, "traded_with_villager"),
            Map.entry(VanillaStatistics.DEATHS, "deaths"),
            Map.entry(VanillaStatistics.MOB_KILLS, "mob_kills"),
            Map.entry(VanillaStatistics.PLAYER_KILLS, "player_kills"),
            Map.entry(VanillaStatistics.FISH_CAUGHT, "fish_caught"),
            Map.entry(VanillaStatistics.ANIMALS_BRED, "animals_bred"),
            Map.entry(VanillaStatistics.LEAVE_GAME, "leave_game"),
            Map.entry(VanillaStatistics.JUMP, "jump"),
            Map.entry(VanillaStatistics.DROP_COUNT, "drop"),
            Map.entry(VanillaStatistics.PLAY_ONE_MINUTE, "play_time"),
            Map.entry(VanillaStatistics.TOTAL_WORLD_TIME, "total_world_time"),
            Map.entry(VanillaStatistics.SNEAK_TIME, "sneak_time"),
            Map.entry(VanillaStatistics.TIME_SINCE_DEATH, "time_since_death"),
            Map.entry(VanillaStatistics.RAID_TRIGGER, "raid_trigger"),
            Map.entry(VanillaStatistics.ARMOR_CLEANED, "clean_armor"),
            Map.entry(VanillaStatistics.BANNER_CLEANED, "clean_banner"),
            Map.entry(VanillaStatistics.ITEM_ENCHANTED, "enchant_item"),
            Map.entry(VanillaStatistics.TIME_SINCE_REST, "time_since_rest"),
            Map.entry(VanillaStatistics.RAID_WIN, "raid_win"),
            Map.entry(VanillaStatistics.TARGET_HIT, "target_hit"),
            Map.entry(VanillaStatistics.CLEAN_SHULKER_BOX, "clean_shulker_box"),
            Map.entry(VanillaStatistics.CAKE_SLICES_EATEN, "eat_cake_slice"),
            Map.entry(VanillaStatistics.CAULDRON_FILLED, "fill_cauldron"),
            Map.entry(VanillaStatistics.BREWINGSTAND_INTERACTION, "interact_with_brewingstand"),
            Map.entry(VanillaStatistics.BEACON_INTERACTION, "interact_with_beacon"),
            Map.entry(VanillaStatistics.NOTEBLOCK_PLAYED, "play_noteblock"),
            Map.entry(VanillaStatistics.CAULDRON_USED, "use_cauldron"),
            Map.entry(VanillaStatistics.NOTEBLOCK_TUNED, "tune_noteblock"),
            Map.entry(VanillaStatistics.FLOWER_POTTED, "pot_flower"),
            Map.entry(VanillaStatistics.TRAPPED_CHEST_TRIGGERED, "trigger_trapped_chest"),
            Map.entry(VanillaStatistics.RECORD_PLAYED, "play_record"),
            Map.entry(VanillaStatistics.FURNACE_INTERACTION, "interact_with_furnace"),
            Map.entry(VanillaStatistics.CRAFTING_TABLE_INTERACTION, "interact_with_crafting_table"),
            Map.entry(VanillaStatistics.SLEEP_IN_BED, "sleep_in_bed"),
            Map.entry(VanillaStatistics.SHULKER_BOX_OPENED, "open_shulker_box"),
            Map.entry(VanillaStatistics.INTERACT_WITH_BLAST_FURNACE, "interact_with_blast_furnace"),
            Map.entry(VanillaStatistics.INTERACT_WITH_SMOKER, "interact_with_blast_furnace"),
            Map.entry(VanillaStatistics.INTERACT_WITH_LECTERN, "interact_with_lectern"),
            Map.entry(VanillaStatistics.INTERACT_WITH_CAMPFIRE, "interact_with_campfire"),
            Map.entry(VanillaStatistics.INTERACT_WITH_CARTOGRAPHY_TABLE, "interact_with_cartography_table"),
            Map.entry(VanillaStatistics.INTERACT_WITH_LOOM, "interact_with_loom"),
            Map.entry(VanillaStatistics.INTERACT_WITH_STONECUTTER, "interact_with_stonecutter"),
            Map.entry(VanillaStatistics.BELL_RING, "bell_ring"),
            Map.entry(VanillaStatistics.INTERACT_WITH_ANVIL, "interact_with_anvil"),
            Map.entry(VanillaStatistics.INTERACT_WITH_GRINDSTONE, "interact_with_grindstone"),
            Map.entry(VanillaStatistics.INTERACT_WITH_SMITHING_TABLE, "interact_with_smithing_table"),
            Map.entry(VanillaStatistics.OPEN_BARREL, "open_barrel"),
            Map.entry(VanillaStatistics.CHEST_OPENED, "open_chest"),
            Map.entry(VanillaStatistics.ENDERCHEST_OPENED, "open_enderchest"),
            Map.entry(VanillaStatistics.HOPPER_INSPECTED, "inspect_hopper"),
            Map.entry(VanillaStatistics.DROPPER_INSPECTED, "inspect_dropper"),
            Map.entry(VanillaStatistics.DISPENSER_INSPECTED, "inspect_dispenser"),
            Map.entry(VanillaStatistics.STRIDER_ONE_CM, "strider_one_cm"),
            Map.entry(VanillaStatistics.MINECART_ONE_CM, "minecart_one_cm"),
            Map.entry(VanillaStatistics.CLIMB_ONE_CM, "climb_one_cm"),
            Map.entry(VanillaStatistics.FLY_ONE_CM, "fly_one_cm"),
            Map.entry(VanillaStatistics.WALK_UNDER_WATER_ONE_CM, "walk_under_water_one_cm"),
            Map.entry(VanillaStatistics.BOAT_ONE_CM, "boat_one_cm"),
            Map.entry(VanillaStatistics.PIG_ONE_CM, "pig_one_cm"),
            Map.entry(VanillaStatistics.HORSE_ONE_CM, "horse_one_cm"),
            Map.entry(VanillaStatistics.CROUCH_ONE_CM, "crouch_one_cm"),
            Map.entry(VanillaStatistics.AVIATE_ONE_CM, "aviate_one_cm"),
            Map.entry(VanillaStatistics.WALK_ONE_CM, "walk_one_cm"),
            Map.entry(VanillaStatistics.WALK_ON_WATER_ONE_CM, "walk_on_water_one_cm"),
            Map.entry(VanillaStatistics.SWIM_ONE_CM, "swim_one_cm"),
            Map.entry(VanillaStatistics.FALL_ONE_CM, "fall_one_cm"),
            Map.entry(VanillaStatistics.SPRINT_ONE_CM, "sprint_one_cm"),
            Map.entry(VanillaStatistics.HAPPY_GHAST_ONE_CM, "happy_ghast_one_cm"),
            Map.entry(VanillaStatistics.NAUTILUS_ONE_CM, "nautilus_one_cm")
    );

    /**
     * @return translation key usable when translating statistics in translation components
     */
    public static String getMinecraftTranslationKey(VanillaStatistic statistic) {
        return statistics.getOrDefault(statistic, statistic.keyStr());
    }
}
