# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.5
maven_group = io.github.steaf23
archives_base_name = bingoreloadedcompanion

# Dependencies
# check this on https://fabricmc.net/develop
fabric_api_version=0.158.0+26.2

modmenu_version=20.0.1