name: BingoReloaded
version: ${version}
author: Steven
main: io.github.steaf23.bingoreloaded.BingoReloadedPaper
api-version: ${minecraft_version}
bootstrapper: io.github.steaf23.bingoreloaded.BingoReloadedBootstrap

dependencies:
  server:
    # hard depend
    packetevents:
      load: BEFORE
      required: true
    # soft depend
    PlaceholderAPI:
      load: BEFORE
      required: false
    MultiWorld:
      load: BEFORE
      required: false

permissions:
  bingo.player:
    description: Players can join teams and play games.
    default: true

  bingo.host:
    description: Start and configure games. Only able to change settings of the current game, cannot make settings presets.
    default: false
    children:
      bingo.player: true

  bingo.admin:
    description: Access all commands and features.
    default: op
    children:
      bingo.host: true